{
  "formatVersion": "1.1",
  "component": {
    "group": "standobyte.jojo",
    "module": "ROTP-public-beta-NeoForge",
    "version": "1.21.1-0.4-260814-a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ROTP-public-beta-NeoForge-1.21.1-0.4-260814-a.jar",
          "url": "ROTP-public-beta-NeoForge-1.21.1-0.4-260814-a.jar",
          "size": 8592424,
          "sha512": "e49ed2aab5524def8525cdb0b77803315dfccaa2749df65f2065881e74f90c994debd2fa40147801dd21eb0ccd75fce839f2c87a32072a5d2d4692756d562adb",
          "sha256": "6ba32d60f8b24f16421141ef15b009b021aceb16ec725dfb6c4af8e50fecd928",
          "sha1": "ae846e8415d5c26b30dffeb945b5a252e92f0a52",
          "md5": "4e685ef44fd906acbe965d88c34378ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "neoforge",
          "version": {
            "requires": "21.1.197"
          }
        },
        {
          "group": "team.unnamed",
          "module": "mocha",
          "version": {
            "strictly": "[3.0.0, 3.1.0)",
            "requires": "[3.0.0, 3.1.0)",
            "prefers": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "ROTP-public-beta-NeoForge-1.21.1-0.4-260814-a.jar",
          "url": "ROTP-public-beta-NeoForge-1.21.1-0.4-260814-a.jar",
          "size": 8592424,
          "sha512": "e49ed2aab5524def8525cdb0b77803315dfccaa2749df65f2065881e74f90c994debd2fa40147801dd21eb0ccd75fce839f2c87a32072a5d2d4692756d562adb",
          "sha256": "6ba32d60f8b24f16421141ef15b009b021aceb16ec725dfb6c4af8e50fecd928",
          "sha1": "ae846e8415d5c26b30dffeb945b5a252e92f0a52",
          "md5": "4e685ef44fd906acbe965d88c34378ae"
        }
      ]
    }
  ]
}
