{
  "formatVersion": "1.1",
  "component": {
    "group": "standobyte.jojo",
    "module": "ROTP-public-beta-NeoForge",
    "version": "1.21.1-0.4-260815-a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ROTP-public-beta-NeoForge-1.21.1-0.4-260815-a.jar",
          "url": "ROTP-public-beta-NeoForge-1.21.1-0.4-260815-a.jar",
          "size": 8605665,
          "sha512": "7daa4fdac79ad08b54162df505bf5c3c540da7c5b61235b141ef1588d5d9f35495ea580bdccc35df152c6d8ffd3160470b0fe468e4cec732644fadb0bdb90b9c",
          "sha256": "0c81872f59468dc88a97a30cfe7a484f38e7de32cad89d18fa20136451d2e8c5",
          "sha1": "2d495d5b540284c8456152e1baf44df2f534349e",
          "md5": "014c3b06ff376f322a30f416410dfbc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "neoforge",
          "version": {
            "requires": "21.1.197"
          }
        },
        {
          "group": "team.unnamed",
          "module": "mocha",
          "version": {
            "strictly": "[3.0.0, 3.1.0)",
            "requires": "[3.0.0, 3.1.0)",
            "prefers": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "ROTP-public-beta-NeoForge-1.21.1-0.4-260815-a.jar",
          "url": "ROTP-public-beta-NeoForge-1.21.1-0.4-260815-a.jar",
          "size": 8605665,
          "sha512": "7daa4fdac79ad08b54162df505bf5c3c540da7c5b61235b141ef1588d5d9f35495ea580bdccc35df152c6d8ffd3160470b0fe468e4cec732644fadb0bdb90b9c",
          "sha256": "0c81872f59468dc88a97a30cfe7a484f38e7de32cad89d18fa20136451d2e8c5",
          "sha1": "2d495d5b540284c8456152e1baf44df2f534349e",
          "md5": "014c3b06ff376f322a30f416410dfbc2"
        }
      ]
    }
  ]
}
