{
  "formatVersion": "1.1",
  "component": {
    "group": "standobyte.jojo",
    "module": "RipplesOfThePast-NeoForge",
    "version": "1.21.1-0.4-251124-b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "RipplesOfThePast-NeoForge-1.21.1-0.4-251124-b.jar",
          "url": "RipplesOfThePast-NeoForge-1.21.1-0.4-251124-b.jar",
          "size": 5425193,
          "sha512": "93c80d1afac718a962ef9b0f599ce62580c86410d1adfc5f61db25590fc0a5b172bcb81737ac46612bdaee4fe7a8ebd51bfefede1e599ff10a51bb55cd163983",
          "sha256": "c15b2f09e38042626cb97f2b098893b63f24e9cc591fc17355926f970f222246",
          "sha1": "b5b3529d784e1b1b46d5c08970d78053fa552d36",
          "md5": "b14d31055451ad5a1c3c26c157df701c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "neoforge",
          "version": {
            "requires": "21.1.197"
          }
        },
        {
          "group": "team.unnamed",
          "module": "mocha",
          "version": {
            "strictly": "[3.0.0, 3.1.0)",
            "requires": "[3.0.0, 3.1.0)",
            "prefers": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "RipplesOfThePast-NeoForge-1.21.1-0.4-251124-b.jar",
          "url": "RipplesOfThePast-NeoForge-1.21.1-0.4-251124-b.jar",
          "size": 5425193,
          "sha512": "93c80d1afac718a962ef9b0f599ce62580c86410d1adfc5f61db25590fc0a5b172bcb81737ac46612bdaee4fe7a8ebd51bfefede1e599ff10a51bb55cd163983",
          "sha256": "c15b2f09e38042626cb97f2b098893b63f24e9cc591fc17355926f970f222246",
          "sha1": "b5b3529d784e1b1b46d5c08970d78053fa552d36",
          "md5": "b14d31055451ad5a1c3c26c157df701c"
        }
      ]
    }
  ]
}
