{
  "formatVersion": "1.1",
  "component": {
    "group": "standobyte.jojo",
    "module": "ROTP-public-beta-NeoForge",
    "version": "1.21.1-0.4-260814-b",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ROTP-public-beta-NeoForge-1.21.1-0.4-260814-b.jar",
          "url": "ROTP-public-beta-NeoForge-1.21.1-0.4-260814-b.jar",
          "size": 8592531,
          "sha512": "9540348a2202b74c97bd2d95651004f494a630110434a6606b932793585f7c1147a812f0c780329eaaae4bb8952a3616c9a63c9059adb765c901ab06992078da",
          "sha256": "568c9b10f2e16a38d9798c62a00956514e5fc497bc844d6b3e6a46de41b0e915",
          "sha1": "22fd03319768b338460bd839c9a79b0904f03ad2",
          "md5": "1c86079e9623608f57bb0c0a5d57fbc9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "neoforge",
          "version": {
            "requires": "21.1.197"
          }
        },
        {
          "group": "team.unnamed",
          "module": "mocha",
          "version": {
            "strictly": "[3.0.0, 3.1.0)",
            "requires": "[3.0.0, 3.1.0)",
            "prefers": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "ROTP-public-beta-NeoForge-1.21.1-0.4-260814-b.jar",
          "url": "ROTP-public-beta-NeoForge-1.21.1-0.4-260814-b.jar",
          "size": 8592531,
          "sha512": "9540348a2202b74c97bd2d95651004f494a630110434a6606b932793585f7c1147a812f0c780329eaaae4bb8952a3616c9a63c9059adb765c901ab06992078da",
          "sha256": "568c9b10f2e16a38d9798c62a00956514e5fc497bc844d6b3e6a46de41b0e915",
          "sha1": "22fd03319768b338460bd839c9a79b0904f03ad2",
          "md5": "1c86079e9623608f57bb0c0a5d57fbc9"
        }
      ]
    }
  ]
}
